apiVersion: v1
kind: Service
metadata:
  name: meta-frontend
  namespace: meta-test
spec:
  type: ClusterIP
  selector:
    app: meta-frontend
  ports:
    - port: 3000
      targetPort: 3000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: meta-ai
  namespace: meta-test
spec:
  type: ClusterIP
  selector:
    app: meta-ai
  ports:
    - port: 8000
      targetPort: 8000
      name: http
